package io.kajelas.touhou.model;

import java.util.Date;

public class TouhouCollection {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column touhou_collection.collection_id
     *
     * @mbggenerated Thu Apr 14 17:10:01 CST 2016
     */
    private Integer collectionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column touhou_collection.collection_name
     *
     * @mbggenerated Thu Apr 14 17:10:01 CST 2016
     */
    private String collectionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column touhou_collection.collection_author
     *
     * @mbggenerated Thu Apr 14 17:10:01 CST 2016
     */
    private String collectionAuthor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column touhou_collection.collection_event
     *
     * @mbggenerated Thu Apr 14 17:10:01 CST 2016
     */
    private String collectionEvent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column touhou_collection.update_time
     *
     * @mbggenerated Thu Apr 14 17:10:01 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column touhou_collection.create_time
     *
     * @mbggenerated Thu Apr 14 17:10:01 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column touhou_collection.add_time
     *
     * @mbggenerated Thu Apr 14 17:10:01 CST 2016
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column touhou_collection.wiki_url
     *
     * @mbggenerated Thu Apr 14 17:10:01 CST 2016
     */
    private String wikiUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column touhou_collection.collection_type
     *
     * @mbggenerated Thu Apr 14 17:10:01 CST 2016
     */
    private String collectionType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column touhou_collection.collection_id
     *
     * @return the value of touhou_collection.collection_id
     *
     * @mbggenerated Thu Apr 14 17:10:01 CST 2016
     */
    public Integer getCollectionId() {
        return collectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column touhou_collection.collection_id
     *
     * @param collectionId the value for touhou_collection.collection_id
     *
     * @mbggenerated Thu Apr 14 17:10:01 CST 2016
     */
    public void setCollectionId(Integer collectionId) {
        this.collectionId = collectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column touhou_collection.collection_name
     *
     * @return the value of touhou_collection.collection_name
     *
     * @mbggenerated Thu Apr 14 17:10:01 CST 2016
     */
    public String getCollectionName() {
        return collectionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column touhou_collection.collection_name
     *
     * @param collectionName the value for touhou_collection.collection_name
     *
     * @mbggenerated Thu Apr 14 17:10:01 CST 2016
     */
    public void setCollectionName(String collectionName) {
        this.collectionName = collectionName == null ? null : collectionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column touhou_collection.collection_author
     *
     * @return the value of touhou_collection.collection_author
     *
     * @mbggenerated Thu Apr 14 17:10:01 CST 2016
     */
    public String getCollectionAuthor() {
        return collectionAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column touhou_collection.collection_author
     *
     * @param collectionAuthor the value for touhou_collection.collection_author
     *
     * @mbggenerated Thu Apr 14 17:10:01 CST 2016
     */
    public void setCollectionAuthor(String collectionAuthor) {
        this.collectionAuthor = collectionAuthor == null ? null : collectionAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column touhou_collection.collection_event
     *
     * @return the value of touhou_collection.collection_event
     *
     * @mbggenerated Thu Apr 14 17:10:01 CST 2016
     */
    public String getCollectionEvent() {
        return collectionEvent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column touhou_collection.collection_event
     *
     * @param collectionEvent the value for touhou_collection.collection_event
     *
     * @mbggenerated Thu Apr 14 17:10:01 CST 2016
     */
    public void setCollectionEvent(String collectionEvent) {
        this.collectionEvent = collectionEvent == null ? null : collectionEvent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column touhou_collection.update_time
     *
     * @return the value of touhou_collection.update_time
     *
     * @mbggenerated Thu Apr 14 17:10:01 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column touhou_collection.update_time
     *
     * @param updateTime the value for touhou_collection.update_time
     *
     * @mbggenerated Thu Apr 14 17:10:01 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column touhou_collection.create_time
     *
     * @return the value of touhou_collection.create_time
     *
     * @mbggenerated Thu Apr 14 17:10:01 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column touhou_collection.create_time
     *
     * @param createTime the value for touhou_collection.create_time
     *
     * @mbggenerated Thu Apr 14 17:10:01 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column touhou_collection.add_time
     *
     * @return the value of touhou_collection.add_time
     *
     * @mbggenerated Thu Apr 14 17:10:01 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column touhou_collection.add_time
     *
     * @param addTime the value for touhou_collection.add_time
     *
     * @mbggenerated Thu Apr 14 17:10:01 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column touhou_collection.wiki_url
     *
     * @return the value of touhou_collection.wiki_url
     *
     * @mbggenerated Thu Apr 14 17:10:01 CST 2016
     */
    public String getWikiUrl() {
        return wikiUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column touhou_collection.wiki_url
     *
     * @param wikiUrl the value for touhou_collection.wiki_url
     *
     * @mbggenerated Thu Apr 14 17:10:01 CST 2016
     */
    public void setWikiUrl(String wikiUrl) {
        this.wikiUrl = wikiUrl == null ? null : wikiUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column touhou_collection.collection_type
     *
     * @return the value of touhou_collection.collection_type
     *
     * @mbggenerated Thu Apr 14 17:10:01 CST 2016
     */
    public String getCollectionType() {
        return collectionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column touhou_collection.collection_type
     *
     * @param collectionType the value for touhou_collection.collection_type
     *
     * @mbggenerated Thu Apr 14 17:10:01 CST 2016
     */
    public void setCollectionType(String collectionType) {
        this.collectionType = collectionType == null ? null : collectionType.trim();
    }

	@Override
	public String toString() {
		return "TouhouCollection [collectionId=" + collectionId + ", collectionName=" + collectionName
				+ ", collectionAuthor=" + collectionAuthor + ", collectionEvent=" + collectionEvent + ", updateTime="
				+ updateTime + ", createTime=" + createTime + ", addTime=" + addTime + ", wikiUrl=" + wikiUrl
				+ ", collectionType=" + collectionType + "]";
	}    
}