package io.kajelas.touhou.dao;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import io.kajelas.touhou.model.TouhouCollection;
import io.kajelas.touhou.model.TouhouCollectionExample.Criteria;
import io.kajelas.touhou.model.TouhouCollectionExample.Criterion;
import io.kajelas.touhou.model.TouhouCollectionExample;
import java.util.List;
import java.util.Map;

public class TouhouCollectionSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table touhou_collection
     *
     * @mbggenerated Thu Apr 14 17:10:01 CST 2016
     */
    public String countByExample(TouhouCollectionExample example) {
        BEGIN();
        SELECT("count(*)");
        FROM("touhou_collection");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table touhou_collection
     *
     * @mbggenerated Thu Apr 14 17:10:01 CST 2016
     */
    public String deleteByExample(TouhouCollectionExample example) {
        BEGIN();
        DELETE_FROM("touhou_collection");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table touhou_collection
     *
     * @mbggenerated Thu Apr 14 17:10:01 CST 2016
     */
    public String insertSelective(TouhouCollection record) {
        BEGIN();
        INSERT_INTO("touhou_collection");
        
        if (record.getCollectionId() != null) {
            VALUES("collection_id", "#{collectionId,jdbcType=INTEGER}");
        }
        
        if (record.getCollectionName() != null) {
            VALUES("collection_name", "#{collectionName,jdbcType=VARCHAR}");
        }
        
        if (record.getCollectionAuthor() != null) {
            VALUES("collection_author", "#{collectionAuthor,jdbcType=VARCHAR}");
        }
        
        if (record.getCollectionEvent() != null) {
            VALUES("collection_event", "#{collectionEvent,jdbcType=VARCHAR}");
        }
        
        if (record.getUpdateTime() != null) {
            VALUES("update_time", "#{updateTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getCreateTime() != null) {
            VALUES("create_time", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getAddTime() != null) {
            VALUES("add_time", "#{addTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getWikiUrl() != null) {
            VALUES("wiki_url", "#{wikiUrl,jdbcType=VARCHAR}");
        }
        
        if (record.getCollectionType() != null) {
            VALUES("collection_type", "#{collectionType,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table touhou_collection
     *
     * @mbggenerated Thu Apr 14 17:10:01 CST 2016
     */
    public String selectByExample(TouhouCollectionExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("collection_id");
        } else {
            SELECT("collection_id");
        }
        SELECT("collection_name");
        SELECT("collection_author");
        SELECT("collection_event");
        SELECT("update_time");
        SELECT("create_time");
        SELECT("add_time");
        SELECT("wiki_url");
        SELECT("collection_type");
        FROM("touhou_collection");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table touhou_collection
     *
     * @mbggenerated Thu Apr 14 17:10:01 CST 2016
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        TouhouCollection record = (TouhouCollection) parameter.get("record");
        TouhouCollectionExample example = (TouhouCollectionExample) parameter.get("example");
        
        BEGIN();
        UPDATE("touhou_collection");
        
        if (record.getCollectionId() != null) {
            SET("collection_id = #{record.collectionId,jdbcType=INTEGER}");
        }
        
        if (record.getCollectionName() != null) {
            SET("collection_name = #{record.collectionName,jdbcType=VARCHAR}");
        }
        
        if (record.getCollectionAuthor() != null) {
            SET("collection_author = #{record.collectionAuthor,jdbcType=VARCHAR}");
        }
        
        if (record.getCollectionEvent() != null) {
            SET("collection_event = #{record.collectionEvent,jdbcType=VARCHAR}");
        }
        
        if (record.getUpdateTime() != null) {
            SET("update_time = #{record.updateTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getCreateTime() != null) {
            SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getAddTime() != null) {
            SET("add_time = #{record.addTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getWikiUrl() != null) {
            SET("wiki_url = #{record.wikiUrl,jdbcType=VARCHAR}");
        }
        
        if (record.getCollectionType() != null) {
            SET("collection_type = #{record.collectionType,jdbcType=VARCHAR}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table touhou_collection
     *
     * @mbggenerated Thu Apr 14 17:10:01 CST 2016
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("touhou_collection");
        
        SET("collection_id = #{record.collectionId,jdbcType=INTEGER}");
        SET("collection_name = #{record.collectionName,jdbcType=VARCHAR}");
        SET("collection_author = #{record.collectionAuthor,jdbcType=VARCHAR}");
        SET("collection_event = #{record.collectionEvent,jdbcType=VARCHAR}");
        SET("update_time = #{record.updateTime,jdbcType=TIMESTAMP}");
        SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        SET("add_time = #{record.addTime,jdbcType=TIMESTAMP}");
        SET("wiki_url = #{record.wikiUrl,jdbcType=VARCHAR}");
        SET("collection_type = #{record.collectionType,jdbcType=VARCHAR}");
        
        TouhouCollectionExample example = (TouhouCollectionExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table touhou_collection
     *
     * @mbggenerated Thu Apr 14 17:10:01 CST 2016
     */
    public String updateByPrimaryKeySelective(TouhouCollection record) {
        BEGIN();
        UPDATE("touhou_collection");
        
        if (record.getCollectionName() != null) {
            SET("collection_name = #{collectionName,jdbcType=VARCHAR}");
        }
        
        if (record.getCollectionAuthor() != null) {
            SET("collection_author = #{collectionAuthor,jdbcType=VARCHAR}");
        }
        
        if (record.getCollectionEvent() != null) {
            SET("collection_event = #{collectionEvent,jdbcType=VARCHAR}");
        }
        
        if (record.getUpdateTime() != null) {
            SET("update_time = #{updateTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getCreateTime() != null) {
            SET("create_time = #{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getAddTime() != null) {
            SET("add_time = #{addTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getWikiUrl() != null) {
            SET("wiki_url = #{wikiUrl,jdbcType=VARCHAR}");
        }
        
        if (record.getCollectionType() != null) {
            SET("collection_type = #{collectionType,jdbcType=VARCHAR}");
        }
        
        WHERE("collection_id = #{collectionId,jdbcType=INTEGER}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table touhou_collection
     *
     * @mbggenerated Thu Apr 14 17:10:01 CST 2016
     */
    protected void applyWhere(TouhouCollectionExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}